#!/bin/sh

basedir="$1"
qtdir="$basedir"/deps
approot="$basedir"/src/scTime.app
sctime="$approot"/Contents/MacOS/scTime
appqtdir="$approot"/Contents/Resources/Qt

echo "Adjusting version number and build date in Info.plist..."
version=`grep ^VERSION $basedir/../../src/src.pro | cut -d" " -f3`
date=`date +"%Y%m%d"`
sed -e "s,@VERSION@,$version,g" \
	-e "s,@DATE@,$date,g" \
	-e "s,@TYPEINFO@,????,g" \
	-e "s,@ICON@,scTime.icns,g" \
	-e "s,@EXECUTABLE@,scTime,g" \
	"$basedir"/Info.plist \
	>"$approot"/Contents/Info.plist || exit 1

echo "Installing Icons into application bundle..."
cp "$basedir"/../../pics/scTime.icns "$approot"/Contents/Resources || \
	exit 1

echo "Copying Qt translations into application bundle..."
rm -rf "$appqtdir"/translations && \
	mkdir -p "$appqtdir"/translations && \
	cp -R "$qtdir"/translations/qt_*.qm "$appqtdir"/translations || \
	exit 1

echo "Creating distribution dmg..."
dmgdir="$basedir"/dmg
dmgname=scTime-"$version"-"$date"
rm -rf "$dmgdir" && \
	rm -f "$dmgname".dmg && \
	mkdir -p "$dmgdir" && \
	rsync -aSH --delete "$approot" "$dmgdir" && \
	hdiutil create "$dmgname".dmg -volname "$dmgname" -srcfolder dmg -fs "HFS+" && \
	rm -rf dmg || \
	exit 1

echo "Done."

exit 0
