#!/bin/sh

builddir="$1"
srcdir="$2"
qtdir="$3"
approot="$builddir"/../../src/scTime.app
sctime="$approot"/Contents/MacOS/scTime
appqtdir="$approot"/Contents/Resources/Qt

patchqmake="$builddir"/patchqmake
patchqtdir="Resources/Qt"

# patch qt library paths in binary itself (not known to exist, but might)
"$patchqmake" "$sctime" "$patchqtdir"

otool -L "$sctime" | grep "/Qt\|/libpq" | sed "s, (compatibility .*$,," | \
	while read lib ; do

	libbase=`echo "$lib" | sed "s,^.*/lib/,,"`
	privatelib="$approot"/Contents/Frameworks/"$libbase"

	# path path to library in main binary
	install_name_tool -change "$lib" @executable_path/../Frameworks/"$libbase" "$sctime"

	# done already
	[ -f "$privatelib" ] && continue

	tdir=`dirname "$privatelib"`
	mkdir -p "$tdir"
	cp "$lib" "$privatelib"

	# path qt library paths in this library
	"$patchqmake" "$privatelib" "$patchqtdir"

	# newer QtGui needs some resources :-(
	dir=`dirname "$lib"`
	if [ -d "$dir"/Resources -a ! -d "$tdir"/Resources ] ; then
		cp -R "$dir"/Resources "$tdir"/Resources
		#ln -s 4 "$tdir"/../Current
		ln -s Versions/4/Resources "$tdir"/../..
	fi

	# change install name of this library
	install_name_tool -id @executable_path/../Frameworks/"$libbase" "$privatelib"

	otool -L $privatelib | grep "/Qt\|/libpq" | sed "s, (compatibility .*$,," | \
		while read sublib ; do

		sublibbase=`echo "$sublib" | sed "s,^.*/lib/,,"`

		# patch path to dependency library in this library
		install_name_tool \
			-change "$sublib" @executable_path/../Frameworks/"$sublibbase" \
			"$privatelib"
	done
done

# adjust version number and build date in Info.plist
version=`grep ^VERSION $srcdir/../../src/src.pro | cut -d" " -f3`
date=`date +"%Y%m%d"`
sed -e "s,@VERSION@,$version,g" \
	-e "s,@DATE@,$date,g" \
	-e "s,@TYPEINFO@,????,g" \
	-e "s,@ICON@,scTime.icns,g" \
	-e "s,@EXECUTABLE@,scTime,g" \
	"$srcdir"/Info.plist \
	>"$approot"/Contents/Info.plist

cp "$srcdir"/../../pics/scTime.icns "$approot"/Contents/Resources

# copy over translations
mkdir -p "$appqtdir"/translations
cp -R "$qtdir"/translations/qt_*.qm "$appqtdir"/translations

# because we patch Qt paths to be relative, some funny logic seems to concat
# the install prefix and translations path ending up with Resources/Qt in the
# file name twice - do some symlinking for that - morons
ln -sfn .. "$appqtdir"/Resources

# clean up
chmod -R go+r $approot
chmod 755 $approot/Contents/MacOS/*
find $approot -name "*.bak" -exec rm -f {} \;
