#!/usr/local/bin/perl
=pod

=head1 NAME

zeitkonten - Liefert Liste von Konten

=head1 SYNOPSIS

zeitkonten [Optionen] [--help]

=head1 DESCRIPTION

Mit diesem Kommando koennen die zur Verfuegung stehenden Konten, eventuell nach Kriterien, aufgelistet werden.

=head1 AUTHOR

Umstellung auf POSTGRESQL C. Haas S+C (07071)9457-232

=head1 VERSION

1.1 01.08.01 

=cut

use lib '/usr/local/zeit';
use Env qw(USER);
use Getopt::Long;
use String::Random;
use DBI;             # Load the module
use CHH_DBPG;

$|=1;

&GetOptions( "konto=s", \$konto,  "gb=s", \$gb,  "help", \$help, "sql", \$sql, "beschreibung", \$beschreibung);

if (defined $help) {
    print "zeitkonten [---konto=name|--gb=name]\n";

    print "Das Kommando gibt listete Konten aus der Zeit Datenbank.\n";
    print "Die Option --konto=name schränkt Auswahl auf Konto=Name ein\n";
    print "Die Option --gb=name schränkt Auswahl auf Geschäftsbereich=Name ein\n";
    print "Die Option --beschreibung gibt zusätzlich eine Beschreibung des Kontos aus.";
    print "\n\nDie Spalten sind: Kontoname, Unterkontoname, Geschäftsbereich, Kostenstelle,(Beschreibung)\n";
    
    exit;
}


$GEMEINSAM="select konto.name,unterkonto.name,gb.name,konto.kostenstelle" ;
if (defined $beschreibung) {
  $GEMEINSAM .= ",unterkonto.beschreibung";
}
$GEMEINSAM .= " from konto,unterkonto,gb";

$GEMEINSAM .= " WHERE konto.konto_id = unterkonto.konto_id AND gb.gb_id = konto.gb_id AND unterkonto.eintragbar=\'y\'";

if (defined $konto) {
  $GEMEINSAM.=" AND konto.name = \'$konto\' ";
}

if (defined $gb) {
    $GEMEINSAM.=" AND gb.name = \'$gb\' ";
}

$GEMEINSAM.=" order by konto.name;";

if ( $sql == 1) {
    print "$GEMEINSAM\n";
}

#open PIPE,"|./chh_zeitsqlwrapper";
#print PIPE $GEMEINSAM;
#close PIPE;
$hostname = "dabaserv";
$dbname   = "zeit";
 
$dbh = &CHH_DBPG::openDB($USER,$hostname,$dbname);
&abfrage;
&CHH_DBPG::closeDB($dbh);
#--------------------------------------------------------------------------
# ENDE Hauptprogramm
#--------------------------------------------------------------------------


#--------------------------------------------------------------------------
# Subroutine  : abfrage
# Beschreibung: 
#--------------------------------------------------------------------------
sub abfrage {
    my $sth = $dbh->prepare("$GEMEINSAM");
    $sth->execute
        or die "Can't execute SQL statement: $DBI::errstr\n";
#print "Konto   \t\t| Unterkonto   \t\t| Gesch.-Ber.\t| Kostenstelle\n";
##       print sprintf "%-30.30s %-20.20s %-20.20s %-10.10s\n","Konto", "Unterkonto", "Gesch.-Ber.", "Kostenst.";
    while (@row = $sth->fetchrow_array()) {
        print "@row\n";
#       print "$row[0]\r\t\t $row[1]\r\t\t\t\t\t $row[2]\r\t\t\t\t\t\t\t $row[3]\n";
##       print sprintf "%-30.30s %-20.20s %-20.20s %-10.10s\n",$row[0], $row[1], $row[2], $row[3];

  }

  $sth->finish;
}


